Fix issue #332 (AttributeError: 'GeAdvantium' object has no attribute 'unit_type') and add 240V Cafe standalone to enum in library (#333)
* v0.6.13 (#299)

* Fix Advantium 'unit_type' error.

Fix "AttributeError: 'GeAdvantium' object has no attribute 'unit_type'" error, by using the personality to determine unit_type.

* Add Advantium 240v Cafe standalone to 240v check.

Requires update from gehome library (pull request submitted there to account for this model).

---------

Co-authored-by: simbaja <59273948+simbaja@users.noreply.github.com>
Co-authored-by: Jack Simbach <jack.simbach@gmail.com>